service: serverless-bootcamp-gft
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam: 
    role:
        statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:scan
              Resource:
                - arn:aws:dynamodb:us-east-1:580687749017:table/Product

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createProduct:
    handler: src/createProduct.handler
    events:
      - http:
          path: /product
          method: post
  fetchProducts:
    handler: src/fetchProducts.handler
    events:
      - http:
          path: /product
          method: get
  fetchProduct:
    handler: src/fetchProduct.handler
    events:
      - http:
          path: /product/{id}
          method: get
  updateProduct:
    handler: src/updateProduct.handler
    events:
      - http:
          path: /product/{id}
          method: put
  
  
resources: 
  Resources:
    Product:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: Product
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
